// Mock data for the Valorant marketplace

export const RANKS = ['Iron', 'Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond', 'Ascendant', 'Immortal', 'Radiant'];

export const REGIONS = ['Mumbai', 'Singapore', 'Hong Kong', 'Tokyo', 'Sydney', 'Seoul'];

export const SKIN_COLLECTIONS = [
  'Champions 2023', 'Reaver', 'Elderflame', 'Prime', 'Sovereign',
  'Glitchpop', 'Spectrum', 'Oni', 'RGX 11z Pro', 'Sentinels of Light',
  'Ion', 'Prelude to Chaos', 'Araxys', 'Magepunk', 'Forsaken'
];

export const listings = [
  {
    id: 'acc-001',
    title: 'Radiant Phantom Collection',
    rank: 'Radiant',
    rankTier: 3,
    level: 412,
    skins: ['Champions 2023 Vandal', 'Reaver Vandal', 'Prime Phantom', 'Elderflame Operator', 'RGX Phantom'],
    skinCount: 87,
    region: 'Mumbai',
    priceRentHour: 45,
    priceRentDay: 350,
    priceBuy: 18500,
    seller: { name: 'ProVault', rating: 4.9, trades: 234, verified: true, avatar: '🛡️' },
    status: 'available',
    featured: true,
    description: 'Top 200 Radiant account with complete Champions collection. All agents unlocked.',
    agents: 22,
    agentsUnlocked: 22,
    createdAt: '2024-12-15',
  },
  {
    id: 'acc-002',
    title: 'Immortal 3 — Full Skin Loadout',
    rank: 'Immortal',
    rankTier: 3,
    level: 356,
    skins: ['Glitchpop Phantom', 'Spectrum Phantom', 'Oni Phantom', 'Reaver Vandal', 'Prime Vandal'],
    skinCount: 64,
    region: 'Mumbai',
    priceRentHour: 35,
    priceRentDay: 280,
    priceBuy: 14200,
    seller: { name: 'SkinKing', rating: 4.8, trades: 189, verified: true, avatar: '👑' },
    status: 'available',
    featured: true,
    description: 'Immortal 3 with Glitchpop + Spectrum bundles. NA/EU ready.',
    agents: 22,
    agentsUnlocked: 20,
    createdAt: '2025-01-02',
  },
  {
    id: 'acc-003',
    title: 'Diamond Starter — Budget Friendly',
    rank: 'Diamond',
    rankTier: 2,
    level: 198,
    skins: ['Prime Vandal', 'Ion Phantom', 'Forsaken Operator'],
    skinCount: 23,
    region: 'Singapore',
    priceRentHour: 18,
    priceRentDay: 140,
    priceBuy: 4800,
    seller: { name: 'BudgetAcc', rating: 4.5, trades: 92, verified: false, avatar: '💎' },
    status: 'available',
    featured: false,
    description: 'Clean diamond account, perfect for competitive play.',
    agents: 22,
    agentsUnlocked: 16,
    createdAt: '2025-02-10',
  },
  {
    id: 'acc-004',
    title: 'Ascendant 3 — Araxys Bundle',
    rank: 'Ascendant',
    rankTier: 3,
    level: 267,
    skins: ['Araxys Vandal', 'Araxys Phantom', 'Araxys Operator', 'Sovereign Ghost', 'Magepunk Sheriff'],
    skinCount: 42,
    region: 'Mumbai',
    priceRentHour: 25,
    priceRentDay: 200,
    priceBuy: 8900,
    seller: { name: 'ValoDeals', rating: 4.7, trades: 156, verified: true, avatar: '🎯' },
    status: 'rented',
    featured: true,
    description: 'Full Araxys collection + multiple vandal skins.',
    agents: 22,
    agentsUnlocked: 19,
    createdAt: '2025-01-18',
  },
  {
    id: 'acc-005',
    title: 'Immortal 1 — Sentinels Edition',
    rank: 'Immortal',
    rankTier: 1,
    level: 301,
    skins: ['Sentinels of Light Vandal', 'Sentinels of Light Operator', 'Glitchpop Judge', 'RGX Vandal'],
    skinCount: 51,
    region: 'Hong Kong',
    priceRentHour: 30,
    priceRentDay: 240,
    priceBuy: 11500,
    seller: { name: 'TrustVault', rating: 4.6, trades: 78, verified: true, avatar: '🔒' },
    status: 'available',
    featured: false,
    description: 'Sentinels bundle complete. All agents unlocked.',
    agents: 22,
    agentsUnlocked: 22,
    createdAt: '2025-03-05',
  },
  {
    id: 'acc-006',
    title: 'Platinum 3 — Oni Collection',
    rank: 'Platinum',
    rankTier: 3,
    level: 145,
    skins: ['Oni Phantom', 'Oni Shorty', 'Prime Guardian', 'Elderflame Frenzy'],
    skinCount: 18,
    region: 'Singapore',
    priceRentHour: 12,
    priceRentDay: 95,
    priceBuy: 3200,
    seller: { name: 'NovaSkins', rating: 4.3, trades: 45, verified: false, avatar: '🌟' },
    status: 'available',
    featured: false,
    description: 'Budget-friendly platinum account with Oni bundle.',
    agents: 22,
    agentsUnlocked: 14,
    createdAt: '2025-02-28',
  },
  {
    id: 'acc-007',
    title: 'Radiant — Champions 2024 Complete',
    rank: 'Radiant',
    rankTier: 1,
    level: 500,
    skins: ['Champions 2023 Vandal', 'Champions 2024 Phantom', 'Spectrum Phantom', 'Elderflame Vandal', 'Reaver Operator'],
    skinCount: 112,
    region: 'Mumbai',
    priceRentHour: 55,
    priceRentDay: 420,
    priceBuy: 25000,
    seller: { name: 'EliteVault', rating: 5.0, trades: 312, verified: true, avatar: '🏆' },
    status: 'available',
    featured: true,
    description: 'The ultimate account. Complete Champions collection, all gun buddies, all agents.',
    agents: 22,
    agentsUnlocked: 22,
    createdAt: '2024-11-20',
  },
  {
    id: 'acc-008',
    title: 'Gold 3 — Fresh Start',
    rank: 'Gold',
    rankTier: 3,
    level: 89,
    skins: ['Ion Sheriff', 'Prime Classic', 'Forsaken Spectre'],
    skinCount: 8,
    region: 'Mumbai',
    priceRentHour: 8,
    priceRentDay: 60,
    priceBuy: 1800,
    seller: { name: 'QuickTrade', rating: 4.1, trades: 34, verified: false, avatar: '⚡' },
    status: 'available',
    featured: false,
    description: 'Clean gold account for casual play or gifting.',
    agents: 22,
    agentsUnlocked: 10,
    createdAt: '2025-03-12',
  },
];

export const activeRentals = [
  {
    id: 'rent-001',
    listingId: 'acc-004',
    title: 'Ascendant 3 — Araxys Bundle',
    rank: 'Ascendant',
    startTime: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    duration: '8 hours',
    totalCost: 360,
    status: 'active',
  },
  {
    id: 'rent-002',
    listingId: 'acc-002',
    title: 'Immortal 3 — Full Skin Loadout',
    rank: 'Immortal',
    startTime: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    duration: '24 hours',
    totalCost: 280,
    status: 'expiring',
  },
];

export const platformStats = {
  totalUsers: 12847,
  totalTrades: 34521,
  trustScore: 98.7,
  activeListings: 1248,
  totalVolume: '₹2.4Cr',
};

export const notifications = [
  { id: 1, type: 'expiry', message: 'Rental "Ascendant 3 — Araxys Bundle" expires in 5 hours', time: '2 min ago', read: false },
  { id: 2, type: 'trade', message: 'Your listing "Radiant Phantom Collection" received a new offer', time: '15 min ago', read: false },
  { id: 3, type: 'system', message: 'Wallet credited: ₹280 from completed rental', time: '1 hour ago', read: true },
  { id: 4, type: 'expiry', message: 'Rental "Immortal 3 — Full Skin Loadout" expiring soon', time: '2 hours ago', read: true },
];

export const purchaseHistory = [
  { id: 'ph-001', title: 'Immortal 2 — Glitchpop Bundle', type: 'buy', amount: 12500, date: '2025-03-01', status: 'completed' },
  { id: 'ph-002', title: 'Diamond 3 — Prime Collection', type: 'rent', amount: 140, date: '2025-02-28', status: 'completed' },
  { id: 'ph-003', title: 'Ascendant 1 — Reaver Set', type: 'rent', amount: 200, date: '2025-02-25', status: 'completed' },
  { id: 'ph-004', title: 'Platinum 2 — Starter', type: 'buy', amount: 2800, date: '2025-02-20', status: 'completed' },
];

export const sellerListings = [
  { ...listings[0], earnings: 12340, rentals: 34, views: 1245 },
  { ...listings[3], earnings: 8920, rentals: 22, views: 890 },
  { ...listings[7], earnings: 2100, rentals: 12, views: 456 },
];

export const adminData = {
  pendingListings: [
    { ...listings[2], submittedAt: '2025-03-15', flagged: false },
    { ...listings[5], submittedAt: '2025-03-14', flagged: true, flagReason: 'Suspicious pricing' },
  ],
  recentActivity: [
    { id: 1, action: 'User registered', user: 'player_2547', time: '5 min ago' },
    { id: 2, action: 'Listing approved', listing: 'Radiant — Champions', admin: 'admin_1', time: '12 min ago' },
    { id: 3, action: 'Rental started', user: 'buyer_891', listing: 'Ascendant 3', time: '30 min ago' },
    { id: 4, action: 'Account flagged', user: 'seller_102', reason: 'Multiple reports', time: '1 hour ago' },
  ],
  stats: {
    totalUsers: 12847,
    totalListings: 1248,
    activeRentals: 347,
    flaggedUsers: 12,
    revenue: 1847500,
  }
};
